### ISSUE TITLE
Unexpected runtime output

### ISSUE THREAD

**Issue by easydaniel** [mit-pdos/biscuit#6]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Building with go version go1.6.2 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
I am building go.img with docker (Linux 16.04) but running QEMU on macOS Mojave with MacBook Pro 15' 2017.

### What did you do?

I run QEMU with 
```sh
make qemu CPUS=1 
```
While I was benchmarking the process creating overhead with the following C program

```cpp
#include "litc.h"
#include <unistd.h>

double create_process_overhead(int times){
    for (int i = 0; i < times; i++) {
        int pid = fork();
        if (pid == 0) exit(0);
        wait(0);
    }
    return 0;
}

int main(void){   
    for (int i = 0; i < 104; ++i) {
        create_process_overhead(500);
    }
    return 0;
}
```
### What did you expect to see?

I expected to see no outputs.

### What did you see instead?

I saw outputs of "POOF" randomly. And as long as I lower the times like calling creating_process_overhead(100), I haven't seen any "POOF" so far.

<img width="396" alt="2018-10-30 10 35 28" src="https://user-images.githubusercontent.com/10112821/47738057-8a7fb900-dc2f-11e8-825e-0395e6b27677.png">

The output only exists when performing forking or pthread_create with large amount of times say 500.
Is it output by Biscuit? But I don't see any possible "POOF" string in the biscuit repository.
Thanks!

**Comment by grodranlorth** [comment]
Biscuit's modified Go runtime prints the "POOF" message (see biscuit/src/runtime/os_linux.go:3133). The runtime prints "POOF" each time it calls munmap() to remind me to fix munap() to not leak pages, as it currently does.

Only a few Kb of memory should be leaked this way, since the runtime only unmaps the old mark bitmaps. Once the size of the kernel heap stabilizes or reaches its max size, the runtime won't print POOF anymore. Thus the POOFs should go away if you run your program a couple times.
